apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
  labels:
    name: mydemo
spec:
  volumes:
    - name: secret-volume-xfusion
      secret:
        secretName: news
  containers:
    - name: secret-container-xfusion
      image: ubuntu:latest
      command: ["sleep", "100"]
      volumeMounts:
        - name: secret-volume-xfusion
          mountPath: /opt/demo