apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012