- name: Create text files and create soft link

  hosts: stapp01, stapp02, stapp03

  become: true

  tasks:

    - name: Create the blog.txt on stapp01

      file:

        path: /opt/finance/blog.txt

        owner: tony

        group: tony

        state: touch

      when: inventory_hostname == "stapp01"

    - name: Create the story.txt on stapp02

      file:

        path: /opt/finance/story.txt

        owner: steve

        group: steve

        state: touch

      when: inventory_hostname == "stapp02"

    - name: Create the media.txt on stapp03

      file:

        path: /opt/finance/media.txt

        owner: banner

        group: banner

        state: touch

      when: inventory_hostname == "stapp03"

    - name: Link /opt/finance directory

      file:

        src: /opt/finance/

        dest: /var/www/html

        state: link